// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using ICities;
using System.Collections.Generic;
using ColossalFramework.Math;
namespace WufireNameGenerator
{
	public class BuildingNameGenerator
	{
		private static BuildingNameData bnd;
		public BuildingNameGenerator ()
		{

		}
		public static void Initialize() {
			bnd = new BuildingNameData();
		}
		public static string GenerateName(ItemClass.SubService subservice, Randomizer randomizer) {
			List<List<string>> nameParts = bnd.BuildingNameDataForSubService(subservice);
			string nameString = "";
			for(int i = 0; i < nameParts.Count; i++) {
				nameString += nameParts[i][randomizer.Int32((uint)nameParts[i].Count)];
				if (i != nameParts.Count - 1) {
					nameString += " ";
				}
			}
			return nameString;
		}
	}
}

