// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using ColossalFramework.Globalization;
using ColossalFramework.Math;
using System;
using System.Collections.Generic;
namespace WufireNameGenerator
{
	internal class IndustrialBuildingNameMod : IndustrialBuildingAI
	{
		//
		// Methods
		//
		public override string GenerateName (ushort buildingID, InstanceID caller)
		{
			string result;
			if (this.m_info.m_prefabDataIndex == -1)
			{
				result = null;
			}
			else
			{
				Randomizer randomizer = new Randomizer ((int)buildingID);
				Random random = new Random ((int)buildingID);
				string text = PrefabCollection<BuildingInfo>.PrefabName ((uint)this.m_info.m_prefabDataIndex);
				uint num = Locale.CountUnchecked ("BUILDING_NAME", text);
				if (num != 0u)
				{
					result = Locale.Get ("BUILDING_NAME", text, randomizer.Int32 (num));
				}
				else
				{
					if (this.m_info.m_class.m_subService == ItemClass.SubService.IndustrialForestry)
					{
						List<string> list = new List<string> (new string[]
						                                      {
							"The",
							"Bunyan's",
							"Decent",
							"Fine",
							"Good",
							"Grizzly",
							"Oak's",
							"Palmer's",
							"Quality",
							"Stumpy's",
							"Willow's",
							"Woody's"
						});
						List<string> list2 = new List<string> (new string[]
						                                       {
							"Cabinet",
							"Forest",
							"Forestry",
							"Log",
							"Lumber",
							"Paper",
							"Plank",
							"Pulp",
							"Timber",
							"Tree",
							"Wood",
							"Woodland"
						});
						List<string> list3 = new List<string> (new string[]
						                                       {
							"Association",
							"Carpenters",
							"Cooperative",
							"Loggers",
							"Lumberjacks",
							"Mill",
							"Organization",
							"Union",
							"Woodcutters"
						});
						int num2 = random.Next (list.Count);
						int num3 = random.Next (list2.Count);
						int num4 = random.Next (list3.Count);
						string text2 = list[num2];
						string text3 = list2[num3];
						string text4 = list3[num4];
						string text5 = string.Concat (new string[]
						                              {
							text2,
							" ",
							text3,
							" ",
							text4
						});
						result = text5;
					}
					else
					{
						if (this.m_info.m_class.m_subService == ItemClass.SubService.IndustrialFarming)
						{
							List<string> list = new List<string> (new string[]
							                                      {
								"The",
								"Beefy",
								"Delicious",
								"Digestible",
								"Edible",
								"Free-Range",
								"Green",
								"Happy",
								"Hardy",
								"Healthy",
								"Henry's",
								"Luke's",
								"Ned's",
								"Natural",
								"Nutritional",
								"Nutritous",
								"Organic",
								"Pam's",
								"Porky's",
								"Ruth's",
								"Scrumptious",
								"Sunny",
								"Sustainable",
								"Tasty"
							});
							List<string> list2 = new List<string> (new string[]
							                                       {
								"Bacon",
								"Cattle",
								"Chicken",
								"Corn",
								"Crop",
								"Crop Circle",
								"Fowl",
								"Grain",
								"Lamb",
								"Livestock",
								"Meat",
								"Potato",
								"Poultry",
								"Steak",
								"Swine",
								"Vegetable",
								"Wheat"
							});
							List<string> list3 = new List<string> (new string[]
							                                       {
								"Company",
								"Cooperative",
								"Estate",
								"Farm",
								"Field",
								"Inc.",
								"Meadow",
								"Pastures",
								"Plains",
								"Range"
							});
							int num2 = random.Next (list.Count);
							int num3 = random.Next (list2.Count);
							int num4 = random.Next (list3.Count);
							string text2 = list[num2];
							string text3 = list2[num3];
							string text4 = list3[num4];
							string text5 = string.Concat (new string[]
							                              {
								text2,
								" ",
								text3,
								" ",
								text4
							});
							result = text5;
						}
						else
						{
							if (this.m_info.m_class.m_subService == ItemClass.SubService.IndustrialOil)
							{
								List<string> list = new List<string> (new string[]
								                                      {
									"The",
									"Clean",
									"Crude",
									"Efficient",
									"Fine",
									"Greasy",
									"Natural",
									"Precise",
									"Productive",
									"Quality",
									"Refined",
									"Safe"
								});
								List<string> list2 = new List<string> (new string[]
								                                       {
									"Drilling",
									"Gas",
									"Gasoline",
									"Kerosene",
									"Jet Fuel",
									"Oil",
									"Petroleum",
									"Petrol",
									"Processing",
									"Propellant",
									"Tar"
								});
								List<string> list3 = new List<string> (new string[]
								                                       {
									"Corporation",
									"Conglomerate",
									"Enterprise",
									"Inc.",
									"Industries",
									"Refinery",
									"Spills",
									"Storage",
									"Syndicate"
								});
								int num2 = random.Next (list.Count);
								int num3 = random.Next (list2.Count);
								int num4 = random.Next (list3.Count);
								string text2 = list[num2];
								string text3 = list2[num3];
								string text4 = list3[num4];
								string text5 = string.Concat (new string[]
								                              {
									text2,
									" ",
									text3,
									" ",
									text4
								});
								result = text5;
							}
							else
							{
								if (this.m_info.m_class.m_subService == ItemClass.SubService.IndustrialOre)
								{
									List<string> list = new List<string> (new string[]
									                                      {
										"The",
										"Brown",
										"Cliff's",
										"Deep",
										"Dwayne's",
										"Family",
										"Gray",
										"Jenkin's",
										"Klondike's",
										"Red",
										"Shiny's",
										"Stone's",
										"Walter's"
									});
									List<string> list2 = new List<string> (new string[]
									                                       {
										"Bedrock",
										"Boulder",
										"Coal",
										"Copper",
										"Dirt",
										"Gold",
										"Gravel",
										"Iron",
										"Mineral",
										"Nugget",
										"Rock",
										"Silver",
										"Steel"
									});
									List<string> list3 = new List<string> (new string[]
									                                       {
										"Association",
										"Company",
										"Conglomerate",
										"Deposit",
										"Enterprise",
										"Mine",
										"Mining",
										"Movers",
										"Pit",
										"Quarry",
										"Reserves",
										"Syndicate"
									});
									int num2 = random.Next (list.Count);
									int num3 = random.Next (list2.Count);
									int num4 = random.Next (list3.Count);
									string text2 = list[num2];
									string text3 = list2[num3];
									string text4 = list3[num4];
									string text5 = string.Concat (new string[]
									                              {
										text2,
										" ",
										text3,
										" ",
										text4
									});
									result = text5;
								}
								else
								{
									List<string> list4 = new List<string> (new string[]
									                                       {
										"The",
										"Basic",
										"Best",
										"Bob's",
										"Cheap",
										"Exotic",
										"Fake",
										"Fred's",
										"Fine",
										"Generic",
										"George's",
										"Good",
										"Handy",
										"Heavy",
										"Lead",
										"Master",
										"Metal",
										"Plastic",
										"Quality",
										"Rare",
										"Simple",
										"Worthy"
									});
									List<string> list5 = new List<string> (new string[]
									                                       {
										"Appliance",
										"Asbestos",
										"Bathtub",
										"Bucket",
										"Clothing",
										"Donut",
										"Fedora",
										"Fish Stick",
										"Furniture",
										"Goods",
										"Hammer",
										"Hat",
										"Item",
										"Paper",
										"Parts",
										"Product",
										"Radio",
										"Rubber Duck",
										"Sprocket",
										"Steam",
										"Tool",
										"Toy",
										"Valve",
										"Widget"
									});
									List<string> list6 = new List<string> (new string[]
									                                       {
										"Assembly",
										"Company",
										"Depot",
										"Factory",
										"Foundry",
										"Inc.",
										"Industries",
										"Makers",
										"Manufactory",
										"Mill",
										"Supplies",
										"Sweatshop",
										"Warehouse"
									});
									int num5 = random.Next (list4.Count);
									int num6 = random.Next (list5.Count);
									int num7 = random.Next (list6.Count);
									string text6 = list4[num5];
									string text7 = list5[num6];
									string text8 = list6[num7];
									string text9 = string.Concat (new string[]
									                              {
										text6,
										" ",
										text7,
										" ",
										text8
									});
									result = text9;
								}
							}
						}
					}
				}
			}
			return result;
		}
	}
}

